{% set name = "dolang" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54473c343d57a84f687a95e01bef1204bb759e69106fbbe7078a796d708f56da

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  always_include_files:
    - dolang/grammar.lark

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - poetry
  run:
    # numba is now an optional dependency
    # - numba >=0.57.1
    - numpy >=1.22.2
    - python >=3.8, <3.12
    - sympy >=1.11.1
    - pyyaml >=6.0
    - lark >=1.1.2

test:
  imports:
    - dolang
    - dolang.tests

about:
  home: https://github.com/EconForge/dolang.py
  license: BSD-2-Clause
  license_family: BSD
  # in the future, don't include the license file
  # as it will be part of the source distribution
  # cf: https://github.com/EconForge/dolang.py/issues/3
  license_file: COPYING
  summary: Dolo Modeling Language

extra:
  recipe-maintainers:
    - albop
